source "https://rubygems.org"
gem 'sass', :path => "~/Projects/sass"
gem 'compass', :path => "~/Projects/compass"
gem 'sinatra'
gem 'heroku'
gem 'guard'
gem 'guard-compass'
gem 'guard-livereload'
gem 'pry'
